version: '3.8'
services:
  gateway:
    build: ./gateway
    image: docker-image-application-gateway:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  server:
    build: ./server
    image: docker-image-application-server:0.0.1
    ports:
      - "9090:9090"
    depends_on:
      - db
    env_file: .db-credentials.env
    environment:
      - SERVER_PORT=9090
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .db-credentials.env