create table if not exists accounts
(
    id       bigint generated by default as identity,
    email    varchar(255),
    username varchar(255),
    primary key (id),
    constraint uk_account_email
        unique (email)
);

create table if not exists item_request
(
    id           bigint generated by default as identity,
    description  varchar(255),
    requestor_id bigint,
    created      timestamp without time zone,
    primary key (id),
    constraint fk_request_requestor
        foreign key (requestor_id) references accounts
);

create table if not exists item
(
    id          bigint generated by default as identity,
    available   boolean,
    description varchar(255),
    name        varchar(255),
    owner_id    bigint,
    request_id  bigint null,
    primary key (id),
    constraint fk_item_owner
        foreign key (owner_id) references accounts,
    constraint fk_item_request
        foreign key (request_id) references item_request
);

create table if not exists booking
(
    id        bigint generated by default as identity,
    finish    timestamp without time zone,
    start     timestamp without time zone,
    status    integer,
    booker_id bigint,
    item_id   bigint,
    primary key (id),
    constraint fk_booking_booker
        foreign key (booker_id) references accounts,
    constraint fk_booking_item
        foreign key (item_id) references item
);

create table if not exists comment
(
    id        bigint generated by default as identity,
    created   timestamp without time zone,
    text      varchar(255),
    author_id bigint,
    item_id   bigint,
    primary key (id),
    constraint fk_comment_author
        foreign key (author_id) references accounts,
    constraint fk_comment_item
        foreign key (item_id) references item
);

